# Generated by Django 4.0.6 on 2022-08-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_rename_quantity_product_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='C',
            new_name='quantity',
        ),
    ]
