# Generated by Django 4.0.6 on 2022-09-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0004_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
